# Generated by Django 4.2.1 on 2024-02-26 12:10

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chat.userprofile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_chat.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='djangochatserver/default.jpg', upload_to='djangochatserver', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='djangochatserver/default_small.jpg', upload_to='djangochatserver', verbose_name='Аватарка маленькая'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_chat.room', verbose_name='Комната'),
        ),
    ]
